apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: test-1
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: ["10.244.0.0/16"]
    serviceDomain: "cluster.local"
  providerSpec:
    value:
      cephAdminKey: "QVFBZGIwQmNGbE52R0JBQXpyS0doUm5Zd3JyY213TzNNTUtsc1E9PQ=="
      cephClientKey: "QVFEcGpVRmNGN1BMR0JBQVVVanRhVDl6emc4V0lPTXJIM3cvU1E9PQ=="
