apiVersion: v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: kube-system
  labels:
    k8s-app: docker-registry
spec:
  replicas: 1
  selector:
    k8s-app: docker-registry
  template:
    metadata:
      labels:
        k8s-app: docker-registry
    spec:
      containers:
      - name: registry
        image: registry:2.5.1
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
      volumes:
      - name: image-store
        hostPath:
          path: /data/registry/
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: docker-system
  labels:
    k8s-app: docker-registry
spec:
  selector:
    k8s-app: docker-registry
  ports:
  - name: registry
    port: 5000
    protocol: TCP
    nodePort: 30500
  type: NodePort
