apiVersion: virtlet.cluster.k8s.io/v1alpha1
kind: VirtletClusterProviderStatus
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: virtletclusterproviderstatus-sample
spec:
  # Add fields here
  foo: bar
